const employees = [
    [
        {
            "employee_id": "001",
            "employee_name": "John Doe",
            "age": 30,
            "job_title": "Web Developer",
            "reporting_manager": "Manager X",
            "employee_type": "Full Time",
            "employee_status": "Probationary",
            "mobile": "123-456-7890",
            "email": "john@example.com",
            "address": "123 Main St, City",
            "salary": 50000,
            "department_id": "002"

        },
        {
            "employee_id": "002",
            "employee_name": "Jane Smith",
            "age": 35,
            "job_title": "Software Engineer",
            "reporting_manager": "Manager Y",
            "employee_type": "Full Time",
            "employee_status": "Permanent",
            "mobile": "987-654-3210",
            "email": "jane@example.com",
            "address": "456 Oak St, Town",
            "salary": 60000,
            "department_id": "002"
        },
        {
            "employee_id": "003",
            "employee_name": "Alice Johnson",
            "age": 28,
            "job_title": "UI/UX Designer",
            "reporting_manager": "Manager Z",
            "employee_type": "Part Time",
            "employee_status": "Permanent",
            "mobile": "555-555-5555",
            "email": "alice@example.com",
            "address": "789 Elm St, Village",
            "salary": 45000,
            "department_id": "002"
        },
        {
            "employee_id": "004",
            "employee_name": "Michael Brown",
            "age": 40,
            "job_title": "Project Manager",
            "reporting_manager": "Manager A",
            "employee_type": "Full Time",
            "employee_status": "Permanent",
            "mobile": "111-222-3333",
            "email": "michael@example.com",
            "address": "456 Maple St, Town",
            "salary": 70000,
            "department_id": "001"
        },
        {
            "employee_id": "005",
            "employee_name": "Emily Wilson",
            "age": 32,
            "job_title": "Marketing Specialist",
            "reporting_manager": "Manager B",
            "employee_type": "Full Time",
            "employee_status": "Permanent",
            "mobile": "444-555-6666",
            "email": "emily@example.com",
            "address": "789 Pine St, Village",
            "salary": 55000,
            "department_id": "001"
        },
        {
            "employee_id": "006",
            "employee_name": "David Lee",
            "age": 38,
            "job_title": "Senior Software Engineer",
            "reporting_manager": "Manager C",
            "employee_type": "Full Time",
            "employee_status": "Permanent",
            "mobile": "777-888-9999",
            "email": "david@example.com",
            "address": "123 Cedar St, City",
            "salary": 75000,
            "department_id": "001"
        },
        {
            "employee_id": "007",
            "employee_name": "Jennifer Taylor",
            "age": 29,
            "job_title": "HR Manager",
            "reporting_manager": "Manager D",
            "employee_type": "Full Time",
            "employee_status": "Permanent",
            "mobile": "123-123-1234",
            "email": "jennifer@example.com",
            "address": "456 Elm St, Town",
            "salary": 65000,
            "department_id": "001"
        },
        {
            "employee_id": "008",
            "employee_name": "Daniel Martinez",
            "age": 35,
            "job_title": "Finance Analyst",
            "reporting_manager": "Manager E",
            "employee_type": "Full Time",
            "employee_status": "Permanent",
            "mobile": "555-666-7777",
            "email": "daniel@example.com",
            "address": "789 Oak St, Village",
            "salary": 60000,
            "department_id": "002"
        },
        {
            "employee_id": "009",
            "employee_name": "Jessica Clark",
            "age": 31,
            "job_title": "Graphic Designer",
            "reporting_manager": "Manager F",
            "employee_type": "Full Time",
            "employee_status": "Permanent",
            "mobile": "888-999-0000",
            "email": "jessica@example.com",
            "address": "123 Pine St, City",
            "salary": 50000,
            "department_id": "002"

        },
        {
            "employee_id": "010",
            "employee_name": "Christopher Harris",
            "mobile": "111-222-3333",
            "email": "christopher@example.com",
            "address": "456 Cedar St, Town",
            "salary": 70000,
            "department_id": "002"
        },
        {
            "employee_id": "011",
            "employee_name": "Amanda White",
            "age": 28,
            "job_title": "Sales Representative",
            "reporting_manager": "Manager H",
            "employee_type": "Full Time",
            "employee_status": "Permanent",
            "mobile": "444-555-6666",
            "email": "amanda@example.com",
            "address": "789 Maple St, Village",
            "salary": 55000,
            "department_id": "001"
        },
        {
            "employee_id": "012",
            "employee_name": "Matthew Rodriguez",
            "age": 36,
            "job_title": "Software Developer",
            "reporting_manager": "Manager I",
            "employee_type": "Full Time",
            "employee_status": "Permanent",
            "mobile": "777-888-9999",
            "email": "matthew@example.com",
            "address": "123 Pine St, City",
            "salary": 75000,
            "department_id": "002"
        },
        {
            "employee_id": "013",
            "employee_name": "Sarah Turner",
            "age": 30,
            "job_title": "Customer Service Representative",
            "reporting_manager": "Manager J",
            "employee_type": "Full Time",
            "employee_status": "Permanent",
            "mobile": "123-123-1234",
            "email": "sarah@example.com",
            "address": "456 Cedar St, Town",
            "salary": 65000,
            "department_id": "001"
        }
    
];

module.exports = employees;